### ISSUE TITLE
Automatically build NLP domain

### ISSUE THREAD

**Issue by bdeboe** [yurimarx/ocr-service#2]
It shouldn't be too hard to automate building the NLP domain after you're adding a new OcrTable record. Either of these approaches should work without much effort:

1. Just call `##class(dc.ocr.OcrNLP).%Build()` after you've added a new record. This will build the whole domain from scratch, so for anything but a demo you'd want to look at [ways to just pick the modified/new records](https://community.intersystems.com/post/keeping-your-iknow-domain-synchronized)

2. Rather than work with a domain that loads from a table, remove the `<table>` data source, make sure to set/keep `allowCustomUpdates="true"` and push the text in directly by using `$SYSTEM.iKnow.IndexString()` as soon as it's OCR'ed

**Comment by yurimarx** [comment]
I tried to use it:
//save the results into database to use text analytics - nlp        
Set ocrTable = ##class(dc.ocr.OcrTable).%New()        
Set ocrTable.FileName = file.Filename        
Set ocrTable.OcrText = pResponse.StringValue         
Set tSC = ocrTable.%Save()

// re-index NLP to the new extracted text        
**Do ##class(dc.ocr.OcrNLP).%Build()** 

But I got:
<text>ERROR #5002: ObjectScript error: &lt;INVALID OREF&gt;zOnProcessInput+35^dc.ocr.OcrService.1</text>

**Comment by bdeboe** [comment]
are you sure that error is for the line with %Build()? [it's a simple class method](https://docs.intersystems.com/iris20203/csp/documatic/%25CSP.Documatic.cls?&LIBRARY=%25SYS&CLASSNAME=%25iKnow.DomainDefinition#METHOD_%25Build), so you should not have any OREFs that could possibly be INVALID.

**Comment by yurimarx** [comment]
you right, but I tried the 2 alternatives, and the oref error goes out, but another error appears, and the error is not printed in the log, I don't have idea what is it.

**Comment by yurimarx** [comment]
@bdeboe I resolved, I was with errors in the status calls only, not related to iKnow, thanks your tip. I choose alternative 2 to your tip
